//QuizList
export const FETCH_QUIZES_START = "FETCH_QUIZES_START";
export const FETCH_QUIZES_SUCCESS = "FETCH_QUIZES_SUCCESS";
export const FETCH_QUIZES_ERROR = "FETCH_QUIZES_ERROR";
export const FETCH_QUIZES_NOT_FOUND = "FETCH_QUIZES_NOT_FOUND";
export const FETCH_QUIZ_END = "FETCH_QUIZ_END";
export const FETCH_QUIZ_SUCCESS = "FETCH_QUIZ_SUCCESS";
export const QUIZ_ANSWER_CLICK = "QUIZ_ANSWER_CLICK";
export const QUIZ_SET_STATE = "QUIZ_SET_STATE";
export const QUIZ_FINISHED = "QUIZ_FINISHED";
export const QUIZ_NEXT_QUESTION = "QUIZ_NEXT_QUESTION";
export const QUIZ_RESET = "QUIZ_RESET";
