//QuizList
export const FETCH_QUIZES_START = "FETCH_QUIZES_START";
export const FETCH_QUIZES_SUCCESS = "FETCH_QUIZES_SUCCESS";
export const FETCH_QUIZES_ERROR = "FETCH_QUIZES_ERROR";
export const FETCH_QUIZES_NOT_FOUND = "FETCH_QUIZES_NOT_FOUND";
export const CLEAR_QUIZES = "CLEAR_QUIZES";
//QUIZ
export const FETCH_QUIZ_END = "FETCH_QUIZ_END";
export const FETCH_QUIZ_SUCCESS = "FETCH_QUIZ_SUCCESS";
export const QUIZ_ANSWER_CLICK = "QUIZ_ANSWER_CLICK";
export const QUIZ_SET_STATE = "QUIZ_SET_STATE";
export const QUIZ_FINISHED = "QUIZ_FINISHED";
export const QUIZ_NEXT_QUESTION = "QUIZ_NEXT_QUESTION";
export const QUIZ_RESET = "QUIZ_RESET";
// QUIZ CREATOR
export const ADD_QUESTION_TO_QUIZ = "ADD_QUESTION_TO_QUIZ";
export const QUIZ_CREATOR_RESET = "QUIZ_CREATOR_RESET";
// CACHE
export const CACHE_QUIZ = "CACHE_QUIZ_CREATOR";
//AUTH
export const AUTH_LOGIN_STARTED = "AUTH_LOGIN_STARTED";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_ERROR = "AUTH_LOGIN_ERROR";

export const AUTH_REGISTER_STARTED = "AUTH_REGISTER_STARTED";
export const AUTH_REGISTER_SUCCESS = "AUTH_REGISTER_SUCCESS";
export const AUTH_REGISTER_ERROR = "AUTH_REGISTER_ERROR";
export const SET_AUTH = "SET_AUTH";
export const SET_USER = "SET_USER";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
